export const OPEN_ADD_FORM = "OPEN_ADD_FORM"
export const CLOSE_ADD_FORM = "CLOSE_ADD_FORM"

export const OPEN_CONFIRM_FORM = "OPEN_CONFIRM_FORM"
export const CLOSE_CONFIRM_FORM = "CLOSE_CONFIRM_FORM"


export const SET_PRONUNCIATION_IN_FORM = "SET_PRONUNCIATION_IN_FORM"
export const SET_MEANING_IN_FORM = "SET_MEANING_IN_FORM"

export const FETCH_WORD_REQUEST = "FETCH_WORD_REQUEST"
export const FETCH_WORD = "FETCH_WORD"

export const ADD_WORD_REQUEST = "ADD_WORD_REQUEST"
export const ADD_WORD = "ADD_WORD"

export const UPDATE_WORD = "UPDATE_WORD"

export const ADD_ACTION_TO_CONFIRM_FORM = "ADD_ACTION_TO_CONFIRM_FORM"
export const SET_CURRENT_WORD_TO_HANDLE = "SET_CURRENT_WORD_TO_HANDLE"
export const DELETE_WORD = "DELETE_WORD"

export const CHANGE_FILTER = "CHANGE_FILTER"

export const ADD_NOTIFICATION = "ADD_NOTIFICATION"
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION"